name: Extended matrix
description: |
  Extend run matrixes above Github's 256 limit.
  Suitable for a two-level nesting.

inputs:
  artifact-id:
    required: true
    description: Identifier to use for uploading a matrix artifact.

  matrix:
    required: true
    description: Matrix as a multiline string, same format as a normal matrix definition.

outputs:
  matrix:
    description: A matrix suitable for extending matrix size workaround.
    value: ${{ steps.extend-matrix.outputs.output }}

runs:
  using: composite

  steps:
    - id: setup-matrix
      uses: druzsan/setup-matrix@v2
      with:
        matrix: ${{ inputs.matrix }}

    - id: extend-matrix
      shell: bash
      run: |
        matrix=$( echo '${{ steps.setup-matrix.outputs.matrix }}' | jq -f ${{ github.action_path }}/extend-matrix.jq )
        echo "matrix=$matrix" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"

    - id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: matrix-${{ inputs.artifact-id }}